main/forms.py
from wtforms import Form, StringField, FileField
from wtforms.validators import InputRequired, ValidationError


class NewDir(Form):
    name = StringField('Введите название новой папки', [InputRequired()])

    def validate_name(form, field):
        forbidden_chars = ('/', ':')
        for char in field.data:
            if char in forbidden_chars:
                raise ValidationError(
                    'Название папки не может содержать: ' + ' ; '.join(forbidden_chars))


class RenameFile(Form):
    name = StringField('Введите новое имя фаила...', [InputRequired()])
    preveousname = StringField('', [InputRequired()])

    def validate_name(form, field):
        forbidden_chars = ('/', ':')
        for char in field.data:
            if char in forbidden_chars:
                raise ValidationError(
                    'Название папки не может содержать: ' + ' ; '.join(forbidden_chars))


class UploadFile(Form):
    file = FileField('Выберите файл для загрузки...', [InputRequired()])
    path = StringField('', [InputRequired()])


class GoogleNewDir(Form):
    name = StringField('Введите название новой папки', [InputRequired()])

    def validate_name(form, field):
        forbidden_chars = ('/', ':')
        for char in field.data:
            if char in forbidden_chars:
                raise ValidationError(
                    'Название папки не может содержать: ' + ' ; '.join(forbidden_chars))


class GoogleRenameFile(Form):
    name = StringField('Введите новое имя фаила...', [InputRequired()])
    id = StringField('', [InputRequired()])

    def validate_name(form, field):
        forbidden_chars = ('/', ':')
        for char in field.data:
            if char in forbidden_chars:
                raise ValidationError(
                    'Название папки не может содержать: ' + ' ; '.join(forbidden_chars))

class GoogleUploadFile(Form):
    file = FileField('Выберите файл для загрузки...', [InputRequired()])

main/views.py
from flask import Blueprint, render_template, url_for, request, jsonify, redirect, make_response
from main.forms import NewDir, RenameFile, UploadFile, GoogleNewDir, GoogleRenameFile, GoogleUploadFile
from flask_login import current_user
import auth.backends as Drive
import os

main = Blueprint('main', __name__, template_folder='template', static_folder='static')


def standart_context(dir):
    context = {
        'form': NewDir(),
        'RenameForm': RenameFile(),
        'UploadForm': UploadFile(),
        'NewDirGoogle': GoogleNewDir(),
        'GoogleRenameFile': GoogleRenameFile(),
        'GoogleUploadForm': GoogleUploadFile()
    }
    dir.update(context)
    return dir


@main.route('/')
def main_page():
    context = standart_context({})
    print('')
    print('')
    print('')
    print(Drive.Yandex.is_authenticated())
    print(Drive.Google.is_authenticated())
    print('')
    print('')
    print('')
    if Drive.Yandex.is_authenticated() or Drive.Google.is_authenticated():
        if Drive.Yandex.is_authenticated():
            context.update(yandex_items=Drive.Yandex.get_rootdir())
        if Drive.Google.is_authenticated():
            context.update(google_items=Drive.Google.get_rootdir())
        #Drive.Yandex.set_current_path('/')
        # When load google_root_dir, set current path call in get_rootdir() method
        return render_template('main/main_page.html', **context)
    else:
        return render_template('main/main_page_isnt_auth.html', **context)


# --------------------------------------------YANDEX--------------------------------------------------------------------#

@main.route('/y/')
def yandex_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.get_rootdir(),
        'google_items': Drive.Google().render_current_path()
        # Drive.Google().get_current_path()
    })
    Drive.Yandex.set_current_path('/')
    return render_template('main/main_page.html', **context)


@main.route('/<path:path>')
def render_yandex_dir(path):
    context = standart_context({
        'yandex_items': Drive.Yandex.get_dir(path),
        'google_items': Drive.Google().render_current_path()
        # Drive.Google().get_current_path()
    })
    Drive.Yandex.set_current_path(path)
    return render_template('main/main_page.html', **context)


@main.route('/ydownload/<path:path>', methods=['GET'])
def yandex_download(path):
    return jsonify(Drive.Yandex.get_download(path))


# -Trash----------------------------------------------------------------------------------------------------------------#

@main.route('/ydelete/<path:path>+<permanent>')
def yandex_delete(path, permanent):
    Drive.Yandex.delete(path, permanent)
    return '', 204


@main.route('/trash/')
def trash_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.trash_get(),
        'google_items': Drive.Google.render_current_path()
        # Drive.Google().get_current_path()
    })
    Drive.Yandex.set_current_path('trash/', 'trash')
    return render_template('main/main_page.html', **context)


@main.route('/yrestore/<path:path>')
def restore_file(path):
    Drive.Yandex.trash_restore(path)
    return '', 204


@main.route('/ytrash_clear/<path:path>')
def yandex_trash_delete(path):
    Drive.Yandex.trash_delete(path)
    return '', 204


# ----------------------------------------------------------------------------------------------------------------------#

@main.route('/ynew_folder/', methods=['POST'])
def yandex_newfolder():
    form = NewDir(request.form)
    if form.validate():
        catalog, parent = Drive.Yandex.get_current_path()
        name = form.name.data
        if catalog == 'root':
            Drive.Yandex.put_mkdir(parent, name)
            return redirect(url_for('main.update_page'))
    else:
        return '', 204


@main.route('/public/')
def public_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.get_root_published_dir(),
        'google_items': Drive.Google.render_current_path()
        # Drive.Google().get_current_path()
    })
    Drive.Yandex.set_current_path('public/', 'public')
    return render_template('main/main_page.html', **context)


@main.route('/yrename/', methods=['POST'])
def rename_file():
    form = RenameFile(request.form)
    if form.validate():
        old_name = form.preveousname.data
        new_name = form.name.data
        Drive.Yandex.rename(old_name, new_name)
    return redirect(url_for('main.update_page'))


@main.route('/ypublish/<path:path>', methods=['GET'])
def yandex_publish(path):
    return jsonify(Drive.Yandex.publish(path))


@main.route('/yunpublish/<path:path>')
def yandex_unpublish(path):
    return Drive.Yandex.unpublish(path)


@main.route('/upd/')
def update_page():
    context = standart_context({
        'yandex_items': Drive.Yandex.render_current_path(),
        'google_items': Drive.Google.render_current_path()
    })
    return render_template('main/main_page.html', **context)


@main.route('/yupload/', methods=['POST'])
def yandex_upload():
    form = UploadFile(request.form)
    file = request.files['file']
    path = form.path.data.strip()
    if path == '/':
        path = ''
    path = path + '/' + file.filename
    Drive.Yandex.put_file(file, path)
    return redirect(url_for('main.update_page'))

@main.route('/yloadfolderss/')
def yandex_load_root():
    items = [item for item in Drive.Yandex.get_dir('/') if item['type'] == 'dir']
    return jsonify(items=items)

@main.route('/yloadfolders/<path:path>')
def yandex_load_folders(path):
    items = [item for item in Drive.Yandex.get_dir(path) if item['type'] == 'dir']
    return jsonify(items=items)

@main.route('/yandexmovefile/')
def yandex_move_file():
    path_from = request.args.get('path_from')
    path_to = request.args.get('path_to', None)
    if path_to is not None:
        path_to = path_to + '/' + request.args.get('name')
    else:
        path_to = request.args.get('name')
    dict = Drive.Yandex.move(path_from, path_to, True)
    return jsonify(dict)
# --------------------------------------------YANDEX--------------------------------------------------------------------#


# --------------------------------------------GOOGLE--------------------------------------------------------------------#

@main.route('/g/')
def google_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.render_current_path(),
        'google_items': Drive.Google.get_rootdir()
    })
    Drive.Yandex.set_current_path('/')
    return render_template('main/main_page.html', **context)


@main.route('/g/<path:_id>')
def render_google_dir(_id):
    context = standart_context({
        'yandex_items': Drive.Yandex.render_current_path(),
        'google_items': Drive.Google.get_dir(_id)
    })
    Drive.Google.set_current_path(_id)
    return render_template('main/main_page.html', **context)


@main.route('/gnew_folder/', methods=['POST'])
def google_newfolder():
    form = GoogleNewDir(request.form)
    if form.validate():
        catalog, parent = Drive.Google.get_current_path()
        name = form.name.data
        if catalog == 'root':
            Drive.Google.put_mkdir(parent, name)
            return redirect(url_for('main.update_page'))
    else:
        return '', 204


@main.route('/gdelete/<path:_id>+<permanent>')
def google_delete(_id, permanent):
    if permanent == 'true':
        Drive.Google.delete_file(_id, True)
    else:
        Drive.Google.delete_file(_id, False)
    return '', 204

@main.route('/gtrash/')
def gtrash_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.render_current_path(),
        'google_items': Drive.Google.trash_get()
    })
    # google set current path in trash get
    return render_template('main/main_page.html', **context)

@main.route('/gpublic/')
def gpublic_root_dir():
    context = standart_context({
        'yandex_items': Drive.Yandex.render_current_path(),
        'google_items': Drive.Google.public_get()
    })
    # google set current path in trash get
    return render_template('main/main_page.html', **context)

@main.route('/grename/', methods=['POST'])
def google_rename_file():
    form = GoogleRenameFile(request.form)
    if form.validate():
        _id = form.id.data
        new_name = form.name.data
        Drive.Google.rename_file(_id, new_name)
        return redirect(url_for('main.update_page'))
    else:
        return '', 204

@main.route('/ggetlink/<itemid>')
def google_download(itemid):
    link = Drive.Google.get_meta(itemid, 'webContentLink').get('webContentLink', None)
    if link is not None:
        return jsonify(href=link)
    else:
        return jsonify(href='Временно функция скачивания папок и некоторых типов файлов недоступна')

@main.route('/gpublish/<itemid>')
def google_publish(itemid):
    Drive.Google.public_file(itemid)
    return '', 204

@main.route('/gunpublish/<itemid>')
def google_unpublish(itemid):
    Drive.Google.unpublic_file(itemid)
    return '', 204

@main.route('/gloadfolderss/')
def google_load_root():
    items = [item for item in Drive.Google.get_rootdir() if item['mimeType'] == 'application/vnd.google-apps.folder']
    return jsonify(items=items)

@main.route('/gloadfolders/<path:_id>')
def google_load_folders(_id):
    items = [item for item in Drive.Google.get_dir(_id) if item['mimeType'] == 'application/vnd.google-apps.folder']
    return jsonify(items=items)

@main.route('/googlemovefile/')
def google_move_file():
    path_from = request.args.get('path_from')
    path_to = request.args.get('path_to', None)
    if path_to is None:
        path_to = Drive.Google.get_root_dir_id()
    dict = Drive.Google.move_file(path_from, path_to)
    return jsonify(dict)

@main.route('/gupload/', methods=['POST'])
def google_upload():
    Drive.Google.put_file(request.files['file'])
    return redirect(url_for('main.update_page'))

templates/main/main_page.html
{% extends 'main.html' %}
{% block content %}
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 disk-main">
			<div class="disk-header">
				<div class="row px-3 pt-2">
					<div class="col p-0">
						{% if 'yandex' in session %}
						<div class="row">
							<div class="col-auto">
								<img src="{{ url_for('static', filename='yandex-logo.png')}}" alt="Yandex-Logo" width="20px" height="20px">
								<span>{{session['yandex']['email']}}</span>
							</div>
							<div class="col-auto">
								<progress value="{{session['yandex']['used_space']}}" max="{{session['yandex']['total_space']}}"></progress>
								<span>{{session['yandex']['used_space']}}/{{session['yandex']['total_space']}} GB</span>
							</div>
						</div>
						{% else %}
						<div class="row">
							<div class="col-auto">
								<img src="{{ url_for('static', filename='yandex-logo.png')}}" alt="Yandex-Logo" width="20px" height="20px">
								<a class='drive_login' href="{{ url_for('auth.yandex_login_request')}}">Привязать аккаунт Yandex</a>
							</div>
						</div>
						{% endif %}
					</div>
					{% if 'yandex' in session %}
						<div class="col-auto align-self-end">
							<a class='drive_logout' href="{{ url_for('auth.yandex_logout')}}">Выход</a>
						</div>
					{% endif %}
				</div>
				{% if 'yandex' in session %}
				<div class="row header-button px-3">
					<!-- buttons -->
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.yandex_root_dir')}}">Файлы</a>
					</div>
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.public_root_dir')}}">Общий доступ</a>
					</div>
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.trash_root_dir')}}">Корзина</a>
					</div>
				</div>
				<div class="row header-button mt-2">
					<div class="col-xl-9 col-lg-9 col-md-9 col-sm-12">
						<div class="d-inline-block text-truncate path_line" id="path_line">
							{{session['yandex']['current_path']}}
						</div>
					</div>
					<div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 p-0">
						<a href="#" class='d-inline-block text-truncate block-close path_line' id='upload-file-link' style="max-width: 90%;">Загрузить файл</a>
					</div>
				</div>
				{% endif %}
			</div>
			{% if 'yandex' in session %}
			<div class="disk-body">
				<div class="row">
					{% if session['yandex']['current_folder'] == 'root' %}
					<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 p-0 mt-2 item">
						<span id='make_new_dir'>
							<div class="row m-0">
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-10 col-10 p-0 order-xl-first order-lg-first order-md-first text-xl-center text-lg-center text-md-center text-sm-left text-left">
									<span class='item_name d-inline-block text-truncate block-close' style="max-width: 90%;">Новая папка</span>
								</div>
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-2 col-2 p-0 order-sm-first order-xs-first order-first text-center">
									<img id='plus_image' src="{{url_for('static', filename='plus.png')}}" style='filter: invert(100%);' class='img-fluid'>
								</div>	
							</div>	
						</span>
					</div>
					{% endif %}
				{% for item in yandex_items %}
					<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 p-0 mt-2 item" id='del{{item["js_path"]}}'>
						<span href="#" title="{{item['name']}}" class="item_link" name='{{item["path"]}}' id='{{item["js_path"]}}' data-type='{{item["type"]}}' data-public='{{item["public"]}}' data-public_url='{{item["public_url"]}}' data-trash='{{item["trash"]}}'>
							<div class="row m-0">
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-10 col-10 p-0 order-xl-first order-lg-first order-md-first text-xl-center text-lg-center text-md-center text-sm-left text-left">
									<span class='item_name d-inline-block text-truncate' style="max-width: 90%;">{{item['name']}}</span>
								</div>
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-2 col-2 p-0 order-sm-first order-xs-first order-first text-center">
									<img src="{{item['image']}}" class='img-fluid' id='{{item["js_path"]}}' alt="">
								</div>	
							</div>	
						</span>
					</div>
				{% endfor %}
				</div>
			</div>
			{% endif %}
		</div>
		<div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 disk-main">
			<div class="disk-header">
				<div class="row px-3 pt-2">
					<div class="col p-0"> 
						{% if 'google' in session %}
						<div class="row">
							<div class="col-auto">
								<img src="{{ url_for('static', filename='google-logo.png')}}" alt="Google-Logo" width="20px" height="20px">
								<span>{{session['google']['email']}}</span>
							</div>
							<div class="col-auto">
								<progress value="{{session['google']['used_space']}}" max="{{session['google']['total_space']}}"></progress>
								<span>{{session['google']['used_space']}}/{{session['google']['total_space']}} GB</span>
							</div>
						</div>
						{% else %}
						<div class="row">
							<div class="col-auto">
								<img src="{{ url_for('static', filename='google-logo.png')}}" alt="Google-Logo" width="20px" height="20px">
								<a class='drive_login' href="{{ url_for('auth.google_login_request')}}">Привязать аккаунт Google</a>
							</div>
						</div>
						{% endif %}
					</div>
					{% if 'google' in session %}
					<div class="col-2 align-self-end">
						<a class='drive_logout' href="{{ url_for('auth.google_logout')}}">Выход</a>
					</div>
					{% endif %}
				</div>
				{% if 'google' in session %}
				<div class="row header-button">
					<!-- buttons -->
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.google_root_dir')}}">Файлы</a>
					</div>
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.gpublic_root_dir')}}">Общий доступ</a>
					</div>
					<div class="col-xl-auto col-lg-auto col-md-auto col-sm-auto p-0">
						<a href="{{url_for('main.gtrash_root_dir')}}">Корзина</a>
					</div>
				</div>
				<div class="row header-button mt-2">
					<div class="col-xl-9 col-lg-9 col-md-9 col-sm-12">
						<div class="d-inline-block text-truncate path_line" id="path_line">
							No-ne
						</div>
					</div>
					<div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 p-0">
						<a href="#" class='d-inline-block text-truncate block-close path_line' id='google-upload-file-link' style="max-width: 90%;">Загрузить файл</a>
					</div>
				</div>
				{% endif %}
			</div>
			<div class="disk-body">
				<div class="row">
					{% if 'google' in session %}
						<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 p-0 mt-2 item">
							<span id='make_new_dir_google'>
								<div class="row m-0">
									<div class="col-xl-12 col-lg-12 col-md-12 col-sm-10 col-10 p-0 order-xl-first order-lg-first order-md-first text-xl-center text-lg-center text-md-center text-sm-left text-left">
										<span class='item_name d-inline-block text-truncate block-close' style="max-width: 90%;">Новая папка</span>
									</div>
									<div class="col-xl-12 col-lg-12 col-md-12 col-sm-2 col-2 p-0 order-sm-first order-xs-first order-first text-center">
										<img id='plus_image' src="{{url_for('static', filename='plus.png')}}" style='filter: invert(100%);' class='img-fluid'>
									</div>	
								</div>	
							</span>
						</div>
						{% for item in google_items %}
							<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 p-0 mt-2 item" id='del{{item["id"]}}'>
							<span href="#" title="{{item['name']}}" class="item_link_google" id='{{item["id"]}}' data-type='{{item["mimeType"]}}' data-trash='{{item["trashed"]}}' data-public='{{item["shared"]}}'>
								<div class="row m-0">
									<div class="col-xl-12 col-lg-12 col-md-12 col-sm-10 col-10 p-0 order-xl-first order-lg-first order-md-first text-x	l-center text-lg-center text-md-center text-sm-left text-left">
										<span class='item_name d-inline-block text-truncate' style="max-width: 90%;">{{item['name']}}</span>
									</div>
									<div class="col-xl-12 col-lg-12 col-md-12 col-sm-2 col-2 p-0 order-sm-first order-xs-first order-first text-center">
										<img src="{{item['image']}}" class='img-fluid' id='{{item["id"]}}' alt="">
									</div>	
								</div>	
							</span>
						</div>
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/main/main_page_isnt_auth.html
{% extends 'main.html' %}

{% block title %}
Авторизация
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row no-gutters">
		<div class="col-xl-2 offset-xl-5 col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-4 offset-sm-4">
			<div id='auth-block'>
				<div class="row align-items-center">
<!--					<div class="col-2 d-block" id='auth-bor-margin'>-->
<!--						<img src="{{ url_for('static', filename='vk-logo.png')}}" alt="Vk-Logo" class='img-fluid'>-->
<!--					</div>-->
<!--					<div class="col-10 text-wrap d-block text-center" id='auth-bor-margin'>-->
<!--						<a href="{{ url_for('auth.vk_login_request')}}" class='auth-a'>Вход через ВКонтакте</a>-->
<!--					</div>-->
					<div class="col-2 d-block" id='auth-bor-margin'>
						<img src="{{ url_for('static', filename='google-logo.png')}}" alt="Google-Logo" class='img-fluid'>
					</div>
					<div class="col-10 text-wrap d-block text-center" id='auth-bor-margin'>
						<a href="{{ url_for('auth.google_login_request') }}" class='auth-a'>Авторизоваться в GoogleDisk</a>
					</div>
					<div class="col-2 d-block" id='auth-bor-margin'>
						<img src="{{ url_for('static', filename='yandex-logo.png')}}" alt="Yandex-Logo" class='img-fluid'>
					</div>
					<div class="col-10 text-wrap d-block text-center" id='auth-bor-margin'>
						<a href="{{ url_for('auth.yandex_login_request') }}" class='auth-a'>Авторизоваться в YandexDisk</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/main/user_page.html
{% extends 'main.html' %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
		{{current_user.vk_name}} {{current_user.vk_lastname}}
		<p>{{current_user.google_drive}}</p>
		<p>{{current_user.yandex_drive}}</p>
		<p>{{current_user.google_drive_email}}</p>
		<p>{{current_user.yandex_drive_email}}</p>
		</div>
	</div>
{% endblock %}